# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b278b7571d0b3bb2b248b04ddb76d049ea9492c6a4c514414d16adf0de39e7d700f9ef597ade21b47c86df96c1f031d275e3febddf709ddfcf80fe61a32ebd

test:
  secret_key_base: 6c2ef0691af61c8b2ee90038481f975e1f8fb4b6ed7d3de5888dfd4f404d64c26051900b03449f123e7c689ea15e695d863432b8a75171d96bf1f6e5b4dcbe53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
